FROM rust:latest as build

RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /usr/src/juno

COPY . .

RUN cargo build --release --target=x86_64-unknown-linux-musl

FROM alpine:latest

WORKDIR /juno

COPY --from=build /usr/src/juno/target/x86_64-unknown-linux-musl/release/juno .

RUN apk add --no-cache dumb-init

CMD ["dumb-init", "--", "/juno/juno"]
